Storekeeper\InventoryBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: Storekeeper\InventoryBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '63'
        description:
            type: string
            length: 255
        hasPicture:
            type: boolean
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: categories
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
