Storekeeper\InventoryBundle\Entity\Inventory\Classification:
    type: entity
    table: null
    repositoryClass: Storekeeper\InventoryBundle\Entity\Inventory\ClassificationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        classId:
            type: integer
            column: classification_id
        name:
            type: string
            length: '63'
        description:
            type: string
            length: 255
        hasPicture:
            type: boolean
        type:
            type: string
            length: '63'
    lifecycleCallbacks: {  }
