Storekeeper\InventoryBundle\Entity\Pack:
    type: entity
    table: null
    repositoryClass: Storekeeper\InventoryBundle\Entity\PackRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        barcode:
            type: string
            length: '127'
        name:
            type: string
            length: '63'
        description:
            type: string
            length: 255
        hasPicture:
            type: boolean
    lifecycleCallbacks: {  }
