Storekeeper\InventoryBundle\Entity\Part:
    type: entity
    table: null
    repositoryClass: Storekeeper\InventoryBundle\Entity\PartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        barcode:
            type: string
            length: '127'
            unique: true
            options:
                comment: 'Barcode'
        name:
            type: string
            length: '63'
            options:
                comment: 'Name of part'
        description:
            type: string
            length: 255
            nullable: true
            options:
                comment: 'Description of part'
        hasPicture:
            type: boolean
            options:
                default: 0
                comment: 'A picture for this part exists'
        isChildIndivisible:
            type: boolean
            options:
                comment: 'This part is integrated to a parent and can t be separated'
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: parts
            required: true
            joinColumn:
                name: category_id
                referencedColumnName: id
        warehouse:
            targetEntity: Warehouse
            inversedBy: parts
            required: true
            joinColumn:
                name: warehouse_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
