Storekeeper\InventoryBundle\Entity\Part:
    type: entity
    table: null
    repositoryClass: Storekeeper\InventoryBundle\Entity\PartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        isChildIndivisible:
            type: boolean
        barcode:
            type: string
            length: '127'
            unique: true
        name:
            type: string
            length: '63'
        description:
            type: string
            length: 255
        hasPicture:
            type: boolean
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: parts
            joinColumn:
                name: category_id
                referencedColumnName: id
        warehouse:
            targetEntity: Warehouse
            inversedBy: parts
            joinColumn:
                name: warehouse_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
