Storekeeper\InventoryBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Storekeeper\InventoryBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: '63'
        password:
            type: string
            length: 255
        auth:
            type: string
            length: '15'
            default: 'local'
        firstname:
            type: string
            length: '63'
            nullable: true
        lastname:
            type: string
            length: '63'
        mail:
            type: string
            length: '63'
    lifecycleCallbacks: {  }
