homepage:
    path:     /
    defaults: { _controller: StorekeeperInventoryBundle:Default:index }

part_view:
    path:     /part/view/{id}
    defaults: { _controller: StorekeeperInventoryBundle:Part:view }

part_edit:
    path:     /part/edit/{id}
    defaults: { _controller: StorekeeperInventoryBundle:Part:edit }
    
    
part_new:
    path:     /part/new
    defaults: { _controller: StorekeeperInventoryBundle:Part:new }
    
part_stats:
    path:     /part/stats
    defaults: { _controller: StorekeeperInventoryBundle:Part:stats }
    
part_list:
    path:     /part/list
    defaults: { _controller: StorekeeperInventoryBundle:Part:list }