Storekeeper\InventoryBundle\Entity\Part:
    properties:
        barcode:
            - Length:
                min: 3
                max: 31
                minMessage: "Le code-barre doit faire au minimum {{ limit }} caractères"
                maxMessage: "Le code-barre doit faire au maximum {{ limit }} caractères"
        name:
            - NotBlank: ~

                

                