<?php

namespace Storekeeper\InventoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WarehouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseRepository extends EntityRepository
{
}
