<?php

namespace Storekeeper\InventoryBundle\Entity\Inventory;

use Doctrine\ORM\EntityRepository;

/**
 * ClassificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationRepository extends EntityRepository
{
}
